### ISSUE TITLE
Javascript  interop error

### ISSUE THREAD

**Issue by chouteau** [SteveSandersonMS/StatefulReconnection#8]
I encountered a JavaScript error while recycling a Blazor site on .NET 8.03.

Stack :

Failed to execute 'querySelector' on 'Document': '#-0rSH5JqnU > DIV:nth-of-type(1) > INPUT:nth-of-type(1)' is not a valid selector. Error: Failed to execute 'querySelector' on 'Document': '#-0rSH5JqnU > DIV:nth-of-type(1) > INPUT:nth-of-type(1)' is not a valid selector. at loadUIState (https://admin.staging.stockasso.com/_content/StatefulReconnection/StatefulReconnection.razor.js:72:35) at Module.init (https://admin.staging.stockasso.com/_content/StatefulReconnection/StatefulReconnection.razor.js:10:5) at https://admin.staging.stockasso.com/_framework/blazor.server.js:1:3244 at new Promise () at y.beginInvokeJSFromDotNet (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:3201) at Yt._invokeClientMethod (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:60713) at Yt._processIncomingData (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:58188) at Yt.connection.onreceive (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:51829) at s.onmessage (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:79974)
at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
at Microsoft.AspNetCore.Components.Web.StatefulReconnection.OnAfterRenderAsync(Boolean firstRender)
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by chouteau** [comment]
I encountered a JavaScript error while recycling a Blazor site on .NET 8.03.

Stack :

Failed to execute 'querySelector' on 'Document': '#-0rSH5JqnU > DIV:nth-of-type(1) > INPUT:nth-of-type(1)' is not a valid selector. Error: Failed to execute 'querySelector' on 'Document': '#-0rSH5JqnU > DIV:nth-of-type(1) > INPUT:nth-of-type(1)' is not a valid selector. at loadUIState (https://admin.staging.stockasso.com/_content/StatefulReconnection/StatefulReconnection.razor.js:72:35) at Module.init (https://admin.staging.stockasso.com/_content/StatefulReconnection/StatefulReconnection.razor.js:10:5) at https://admin.staging.stockasso.com/_framework/blazor.server.js:1:3244 at new Promise () at y.beginInvokeJSFromDotNet (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:3201) at Yt._invokeClientMethod (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:60713) at Yt._processIncomingData (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:58188) at Yt.connection.onreceive (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:51829) at s.onmessage (https://admin.staging.stockasso.com/_framework/blazor.server.js:1:79974)
--------------------------------------------
at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
at Microsoft.AspNetCore.Components.Web.StatefulReconnection.OnAfterRenderAsync(Boolean firstRender)
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by CodeFontana** [comment]
It's my understanding that this repository is designed for Blazor on .NET 6 & 7, and is not compatible with the changes made in .NET 8.
